### PR TITLE
Add function to get all items from a playlist

### PR DESCRIPTION
**Pull request by razcore-art**
Hey there, nice module you got here.

So unless I'm missing something very obvious... there's no way to get all the items in a playlist. You're limited by `maxResults` if we'd use `get_playlist_items()` so I added a function called `get_playlist_all_items()` that isn't limited by this. I'm using it on playlists larger than 50 so I needed this functionality. Feel free to use the function... or not :)

Thanks anyway.

### CODE REVIEW

**Comment by MerleLiuKun** [comment]
Thanks for your pr. I know what your mean. Before I think retrieve all items may be let the instance too big. Ok, I think this is necessary. I will add this quickly. 

Thank you again.

**Comment by razcore-art** [comment]
Thanks for your quick response. I understand what you're saying. It can be bad with long lists. Notice I still kept the `count` parameter in case someone wants to limit the results, it's just that by default it grabs all videos in a list.

**Comment by MerleLiuKun** [comment]
Yes, you are right. And I think this method almost same as the `get_playlist_items` just the result count is different. 

So I think If use the `get_playlist_items` method and provide the parameter `count`  with `None`,  the method will return all items. 

What do you think this?  :)

**Comment by razcore-art** [comment]
Yes, that's what I'd do. If `count` is `None` then get all videos.

Just a quick observation. The `limit` parameter is a bit confusing especially if you don't know the Google API (like myself). I would remove it entirely since it can't be used anyway. I mean you are returning the full list no matter what `limit` is. I know this is to set `maxResults`, but it seems more like  an internal technical thing.

I don't know if it's better to set `maxResults` to max or not, but I'd still remove `limit`.

This goes for all functions that use `limit` as a parameter.

**Comment by MerleLiuKun** [comment]
Yes, provide the `limit` parameter, just follow the YouTube API, Maybe always set this with the max number is better. 

For me, the reason provide this is only my app has less cost quota. So use this can save some cost. :see_no_evil: 

And I just modify the code, I think it is what you want. Can you have a look?

**Comment by razcore-art** [comment]
Yep, seems to be working, although now I'm getting an error if I use too many ids with `get_video_by_id` :). I'll check it out

**Comment by MerleLiuKun** [comment]
:100: , OK. I will modify the other apis to get all items. And publish new version soon. 

If you have any other question, can contact me. I am happy if I can provide some help.  

Thanks again for your help for this library.

**Comment by razcore-art** [comment]
Glad to help and thanks for the quick responses :). I will definitely try and improve it if I find something isn't working right or as expected. Thanks again

**Comment by MerleLiuKun** [comment]
:). Have a good day :smile: !

**Pull request merged**
